---

- name: Manage users dotfiles
  shell: |
    if ! [ -e "$HOME/.yadm/repo.git" ] ; then
        yadm clone --bootstrap "{{ item.dotfiles_repo | d(users__dotfiles_repo) }}"
    else
        yadm pull
    fi
  with_flattened:
    - '{{ users__default_accounts }}'
    - '{{ users__admin_accounts }}'
    - '{{ users__accounts }}'
    - '{{ users__group_accounts }}'
    - '{{ users__host_accounts }}'
    - '{{ users__dependent_accounts }}'
  become: True
  become_user: '{{ item.name }}'
  check_mode: False
  register: users__register_dotfiles
  changed_when: ('Already up-to-date.' not in users__register_dotfiles.stdout_lines)
  when: (item.name|d() and item.state|d('present') != 'absent' and item.createhome|d(True) and
         (item.dotfiles | d(item.dotfiles_enabled | d(users__dotfiles_enabled))) | bool and
         (item.dotfiles_repo | d(users__dotfiles_repo)))
  no_log: '{{ users__no_log | bool }}'
