---

- name: Manage memcached server
  hosts: [ 'debops_service_memcached' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.etc_services
      tags: [ 'role::etc_services', 'skip::etc_services' ]
      etc_services__dependent_list:
        - '{{ memcached__etc_services__dependent_list }}'

    - role: debops.ferm
      tags: [ 'role::ferm', 'skip::ferm' ]
      ferm__dependent_rules:
        - '{{ memcached__ferm__dependent_rules }}'

    - role: debops.memcached
      tags: [ 'role::memcached', 'skip::memcached' ]
