---

- name: 'Manage Prometheus server'
  hosts: [ 'debops_service_prometheus_server' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:
    - role: debops.apt_preferences
      tags: [ 'role::apt_preferences', 'role::prometheus' ]
      apt_preferences__dependent_list:
        - '{{ prometheus_server__apt_preferences__dependent_list }}'
        - '{{ nginx__apt_preferences__dependent_list if prometheus_server__nginx else [] }}'

    - role: debops.etc_services
      tags: [ 'role::etc_services' ]
      etc_services__dependent_list: '{{ prometheus_server__etc_services__dependent_list }}'

    - role: debops.ferm
      tags: [ 'role::ferm', 'role::prometheus' ]
      ferm__dependent_rules:
        - '{{ prometheus_server__ferm__dependent_rules }}'
        - '{{ nginx__ferm__dependent_rules if prometheus_server__nginx else [] }}'

    - role: debops.nginx
      tags: [ 'role::nginx' ]
      nginx__dependent_servers: '{{ prometheus_server__nginx__dependent_servers }}'
      nginx__dependent_htpasswd: '{{ prometheus_server__nginx__dependent_htpasswd }}'
      when: prometheus_server__nginx

    - role: debops.prometheus_server
      tags: [ 'role::prometheus' ]
